### ISSUE TITLE
Add Gain Schedules

### ISSUE THREAD

**Issue by chrishajduk84** [UWARG/PICpilot#1]
Add ways to change the PID loop (Control Loop) gains dynamically based on changing conditions. For instance, if the airspeed is between x and y, change the roll gain to z.

**Comment by sergei1152** [comment]
lmao the milestones

**Comment by chrishajduk84** [comment]
Lol.  It kept getting pushed off...

**Comment by ianjfrosst** [comment]
Should this be something implemented in the ground station, rather than the PICpilot?

**Comment by chrishajduk84** [comment]
Debatable. The counterpoint is that if you have it on the groundstation you need to send a new set of gains whenever the air speed changes significantly and this adds traffic to the datalink. 

If it happens onboard, there is no datalink dependency. 

Either way,  by implementing this feature you end up making the system more complicated, which I'm not sure is the best idea.

**Comment by sergei1152** [comment]
I don't think this is a feature we should implement at all tbh,  unless there's a valid book or article that describes the advantages of gain schedules,  with test results.  So far from a Google search I hadn't seen anything. Ardupilot doesn't implement it,  and it's a pretty stable system.

**Comment by ianjfrosst** [comment]
So is this necessary, or can this issue (finally) be closed?

**Comment by chrishajduk84** [comment]
I think it can be closed. It's outside the scope of what we usually do.
