### ISSUE TITLE
Remove meta/generated files in the project and ignore them.

### ISSUE THREAD

**Issue by CoatedMoose** [UWARG/PICpilot#13]
Pretty much everything in the nbproject (except for _____???) are generated files. These should be removed and .gitignore'd as appropriate. This will prevent the emergence of future merge conflicts on these files, which we don't actually need/want to deal with (since they are generated anyway).

**Comment by chrishajduk84** [comment]
Cleaned up as much as possible. The remaining files depict important settings such as the chip being used, the files in the project, etc.
