### ISSUE TITLE
Input Capture Pin 7 Doesn't Work (I don't believe) is this why?

### ISSUE THREAD

**Issue by mehatfie** [UWARG/PICpilot#29]
![image](https://cloud.githubusercontent.com/assets/3779150/7335272/18ea5dec-eb81-11e4-98da-044f6e78237c.png)

in AttitudeManager.c ~line 145

**Comment by sergei1152** [comment]
@chrishajduk84 lmao

**Comment by chrishajduk84** [comment]
Lol ignorance is bliss.
