### ISSUE TITLE
Test and fix integral control in autopilot

### ISSUE THREAD

**Issue by chrishajduk84** [UWARG/PICpilot#3]
We have never used integral control while flying. The code is partially there, however it needs to be completed and fixed.

-Make sure there is no overflow in the integral summation (make sure it doesn't max out)

The best option may  be to convert all the control loops back into floating point calculations, and optimize the code elsewhere.

**Comment by ianjfrosst** [comment]
Working on this right now at https://github.com/ianjfrosst/PICpilot/tree/orientation_rewrite. Implemented a general interface for PID loops, which includes some integral control protection.

**Comment by ianjfrosst** [comment]
Fixed in #107

**Comment by ianjfrosst** [comment]
Fixed in #107
